[profile.default]
# src = "src"
# out = "out"
# libs = ["lib"]

remappings = [
	'lib/ens-contracts:@openzeppelin/contracts=lib/openzeppelin-contracts-v4.9/contracts/',
	'@ensdomains/ens-contracts/=lib/ens-contracts/',
	'@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
]

optimizer = true
optimizer_runs = 1000
